apiVersion: apps/v1
kind: Deployment
metadata:
  name: igrp-platform-access-management-backend
  namespace: igrp-platform-access-management-backend
  labels:
    app: igrp-platform-access-management-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igrp-platform-access-management-backend
  template:
    metadata:
      labels:
        app: igrp-platform-access-management-backend
    spec:
      containers:
        - name: igrp-platform-access-management-backend
          image: docker.io/irnzing/irn:igrp-platform-access-management
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: igrp-platform-access-management-backend-conf
            - secretRef:
                name: igrp-platform-access-management-backend-secret