apiVersion: v1
kind: Secret
metadata:
  name: igrp-platform-access-management-backend-secret
  namespace: igrp-platform-access-management-backend
type: Opaque
stringData:
  IGRP_KEYCLOAK_CLIENT_ID: "access-management"
  IGRP_KEYCLOAK_CLIENT_SECRET: "FTpKJk9kIT2LBCpzIAzCDZfHfjbqzWCy"

  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"

  DATABASE_PASSWORD: "postgres"
  DATABASE_USERNAME: "postgres"
  DATABASE_URL: "jdbc:postgresql://igrp-platform-access-management-backend-db:5432/postgres"


