apiVersion: apps/v1
kind: Deployment
metadata:
  name: access-management
  labels:
    app: access-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: access-management
  template:
    metadata:
      labels:
        app: access-management
    spec:
      containers:
        - name: access-management
          image: registry.nosi.cv/igrp/access-management-api:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: EUREKA_SERVICE_URL
              value: "https://igrp-cloud-eureka-napg-staging-1.up.railway.app/eureka/"
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m -XX:+UseG1GC"
            - name: SERVER_PORT
              value: "8080"
            - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
              value: "true"
            - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID
              value: "true"
            - name: SPRING_PROFILES_ACTIVE
              value: "development"
