apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-pod-service-reader
  namespace: igrp-process-studio-backend
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-pod-service-reader-binding
  namespace: igrp-process-studio-backend
subjects:
  - kind: ServiceAccount
    name: default
    namespace: igrp-process-studio-backend
roleRef:
  kind: Role
  name: k8s-pod-service-reader
  apiGroup: rbac.authorization.k8s.io