apiVersion: apps/v1
kind: Deployment
metadata:
  name: igrp-process-studio-frontend
  labels:
    app: igrp-process-studio-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: igrp-process-studio-frontend
  template:
    metadata:
      labels:
        app: igrp-process-studio-frontend
    spec:
      containers:
        - name: igrp-process-studio-frontend
          image: ${REGISTRY_URL}/${REGISTRY_PROJECT}/${REGISTRY_IMAGE}:${REGISTRY_TAG}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: API_GATEWAY
              value: "https://${{igrp-cloud-gateway-iE5d.RAILWAY_PUBLIC_DOMAIN}}/igrp-platform-process-management-studio"
            - name: IGRP_APP_BASE_PATH
              value: ""
            - name: IGRP_APP_CENTER_URL
              value: "https://${{igrp-application-center.RAILWAY_PUBLIC_DOMAIN}}"
            - name: IGRP_APP_CODE
              value: "demo"
            - name: IGRP_APP_HOME_SLUG
              value: "/process"
            - name: IGRP_APP_MANAGER_API
              value: "https://${{igrp-cloud-gateway-iE5d.RAILWAY_PUBLIC_DOMAIN}}/igrp-access-management"
            - name: IGRP_APP_NAME_DESCRIPTION
              value: "YOUR APP DESCRIPTION NAME"
            - name: IGRP_LOGIN_URL
              value: "/login"
            - name: IGRP_LOGOUT_URL
              value: "/logout"
            - name: IGRP_NEXTAUTH_CALLBACK
              value: "https://${{RAILWAY_PUBLIC_DOMAIN}}/api/auth/callback"
            - name: IGRP_PREVIEW_MODE
              value: "true"
            - name: KEYCLOAK_CLIENT_ID
              value: "access-management"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "FTpKJk9kIT2LBCpzIAzCDZfHfjbqzWCy"
            - name: KEYCLOAK_ISSUER
              value: "https://${{igrp-iam-keycloak-ztlw.RAILWAY_PUBLIC_DOMAIN}}/realms/igrp"
            - name: NEXT_PUBLIC_API_GATEWAY
              value: "https://${{igrp-cloud-gateway-iE5d.RAILWAY_PUBLIC_DOMAIN}}"
            - name: NEXTAUTH_SECRET
              value: "LlCNqCMrPIIXdLDQhTlGgADscUrXCloy"
            - name: NEXTAUTH_URL
              value: "https://${{RAILWAY_PUBLIC_DOMAIN}}/api/auth"