apiVersion: apps/v1
kind: Deployment
metadata:
  name: igrp-process-studio-frontend
  namespace: igrp-process-studio-frontend
  labels:
    app: igrp-process-studio-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igrp-process-studio-frontend
  template:
    metadata:
      labels:
        app: igrp-process-studio-frontend
    spec:
      containers:
        - name: igrp-process-studio-frontend
          image: docker.io/irnzing/irn:igrp-process-studio-frontend-with-basepath
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: igrp-process-studio-frontend-conf
            - secretRef:
                name: igrp-process-studio-frontend-secret
          livenessProbe:
            httpGet:
              path: /apps/igrp-process-management/api/health
              port: 3000
            initialDelaySeconds: 10   # wait 10s after container start
            periodSeconds: 15         # check every 15s
            timeoutSeconds: 3         # fail if no response in 3s
            failureThreshold: 3       # restart if 3 consecutive fails
          readinessProbe:
            httpGet:
              path: /apps/igrp-process-management/api/health
              port: 3000
            initialDelaySeconds: 5    # readiness checked earlier
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3