apiVersion: apps/v1
kind: Deployment
metadata:
  name: igrp-platform-access-management
  labels:
    app: igrp-platform-access-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: igrp-platform-access-management
  template:
    metadata:
      labels:
        app: igrp-platform-access-management
    spec:
      containers:
        - name: igrp-platform-access-management
          image: irnzing/irn:igrp-platform-access-management
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: AUTH_JWT_ISSUER
              value: "https://${{igrp-iam-keycloak-ztlw.RAILWAY_PUBLIC_DOMAIN}}/realms/igrp"
            - name: ENABLE_SWAGGER
              value: "true"
            #- name: IGRP_KEYCLOAK_CLIENT_ID      apenas no .env.example
            #  value: "access-management"
            #- name: IGRP_KEYCLOAK_CLIENT_SECRET     apenas no .env.example
            #  value: "FTpKJk9kIT2LBCpzIAzCDZfHfjbqzWCy"
            #- name: IGRP_KEYCLOAK_GRANT_TYPE         apenas no .env.example
            #  value: "client_credentials"
            #- name: IGRP_KEYCLOAK_REALM          apenas no .env.example
            #  value: "igrp"
            #- name: IGRP_KEYCLOAK_SERVER_URL       apenas no .env.example
            #  value: "https://${{igrp-iam-keycloak-ztlw.RAILWAY_PUBLIC_DOMAIN}}"
            #- name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE      não existe
            #  value: "health,info"
            - name: MINIO_ACCESS_KEY
              value: "${{minio-bucket-FNSX.MINIO_ROOT_USER}}"
            - name: MINIO_BUCKET_NAME
              value: "igrp"
            - name: MINIO_PORT
              value: "${{minio-bucket-FNSX.PORT}}"
            - name: MINIO_SECRET_KEY
              value: "${{minio-bucket-FNSX.MINIO_ROOT_PASSWORD}}"
            - name: MINIO_SECURITY
              value: "false"
            - name: MINIO_URL
              value: "${{minio-bucket-FNSX.RAILWAY_PRIVATE_DOMAIN}}"
            #- name: OTEL_ENABLED             apenas no .env.example
            #  value: "false"
            - name: POSTGRES_DATABASE
              value: "${{igrp-database-postgres-2.POSTGRES_DB}}"
            - name: POSTGRES_HOST
              value: "${{igrp-database-postgres-2.PGHOST}}"
            - name: POSTGRES_PASSWORD
              value: "${{igrp-database-postgres-2.POSTGRES_PASSWORD}}"
            - name: POSTGRES_PORT
              value: "${{igrp-database-postgres-2.PGPORT}}"
            - name: POSTGRES_USER
              value: "${{igrp-database-postgres-2.POSTGRES_USER}}"
            #- name: SERVICE_NAME            apenas no .env.example
            #  value: "igrp-platform-accessmanagement-service"
            - name: SERVICE_PORT
              value: "8080"
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "true"
            #- name: SPRING_DATA_REDIS_URL       não existe
            #  value: "${{Redis.REDIS_URL}}"
            #- name: SPRING_ACTIVE_PROFILE      não existe
            #  value: "production"
          
