apiVersion: apps/v1
kind: Deployment
metadata:
  name: igrp-process-management-backend-api
  labels:
    app: igrp-process-management-backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: igrp-process-management-backend-api
  template:
    metadata:
      labels:
        app: igrp-process-management-backend-api
    spec:
      containers:
        - name: igrp-process-management-backend-api
          image: irnzing/irn:igrp-process-management-backend-api
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: AUTH_JWT_ISSUER
              value: "https://${{igrp-iam-keycloak-ztlw.RAILWAY_PUBLIC_DOMAIN}}/realms/igrp_iam"
            - name: ENABLE_SWAGGER
              value: "true"
            - name: IGRP_MAIL_DEFAULT_FROM
              value: "no-reply@igrp.cv"
            - name: LOGGING_LEVEL_APP
              value: "DEBUG"
            - name: LOGGING_LEVEL_ROOT
              value: "INFO"
            - name: LOGGING_LEVEL_SPRING_WEB
              value: "DEBUG"
            - name: POSTGRES_DATABASE
              value: "${{igrp-process-runtime-postgres-o66-.POSTGRES_DB}}"
            - name: POSTGRES_HOST
              value: "${{igrp-process-runtime-postgres-o66-.PGHOST}}"
            - name: POSTGRES_PASSWORD
              value: "${{igrp-process-runtime-postgres-o66-.POSTGRES_PASSWORD}}"
            - name: POSTGRES_PORT
              value: "${{igrp-process-runtime-postgres-o66-.PGPORT}}"
            - name: POSTGRES_USER
              value: "${{igrp-process-runtime-postgres-o66-.POSTGRES_USER}}"
            #- name: SERVICE_NAME    # apenas existe no .env.example
            #  value: "igrp-process-management-service"
            #- name: SERVICE_PORT    # apenas existe no .env.example e profile development
            #  value: "8080"
            - name: SPRING_ACTIVE_PROFILE  # default application.properties
              value: "production"
            - name: SPRING_MAIL_HOST
              value: "smtp.gmail.com"
            - name: SPRING_MAIL_PASSWORD
              value: "password"
            - name: SPRING_MAIL_PORT
              value: "587"
            - name: SPRING_MAIL_SMTP_AUTH
              value: "true"
            - name: SPRING_MAIL_SMTP_STARTTLS_ENABLE
              value: "true"
            - name: SPRING_MAIL_USERNAME
              value: "user@gmail.com"