apiVersion: v1
kind: Secret
metadata:
  name: Igrp-process-runtime-backend-secret
  namespace: TO BE DEFINED
type: Opaque
stringData:
  POSTGRES_DATABASE: "TO BE DEFINED BY IRN"
  POSTGRES_PASSWORD: "TO BE DEFINED BY IRN"
  POSTGRES_PORT: "TO BE DEFINED BY IRN"
  POSTGRES_USER: "TO BE DEFINED BY IRN"
  POSTGRES_HOST: "TO BE DEFINED BY IRN"
  SPRING_MAIL_PASSWORD: "password"


