apiVersion: v1
kind: Secret
metadata:
  name: igrp-process-runtime-backend-secret
  namespace: igrp-process-runtime-backend
type: Opaque
stringData:
  POSTGRES_DATABASE: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "igrp-process-runtime-backend-db"
  SPRING_MAIL_PASSWORD: "password"


