apiVersion: apps/v1
kind: Deployment
metadata:
  name: igrp-application-center-frontend
  namespace: igrp-application-center-frontend
  labels:
    app: igrp-application-center-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: igrp-application-center-frontend
  template:
    metadata:
      labels:
        app: igrp-application-center-frontend
    spec:
      containers:
        - name: igrp-application-center-frontend
          image: docker.io/irnzing/irn:igrp-application-center
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: igrp-application-center-frontend-conf
            - secretRef:
                name: igrp-application-center-frontend-secret