apiVersion: v1
kind: ConfigMap
metadata:
  name: irn-process-management-demo-frontend-conf
  namespace: TO BE DEFINED
data:
  API_GATEWAY: "TO BE DEFINED - igrp-cloud-gateway_PUBLIC_DOMAIN/igrp-platform-process-management"
  IGRP_APP_BASE_PATH: ""
  IGRP_APP_CENTER_URL: "TO BE DEFINED - igrp-application-center_PUBLIC_DOMAIN"
  IGRP_APP_CODE: "APP_IGRP_CENTER"
  IGRP_APP_HOME_SLUG: "/fila-de-trabalho"
  IGRP_APP_MANAGER_API: "TO BE DEFINED - igrp-cloud-gateway_PUBLIC_DOMAIN/igrp-access-management"
  IGRP_APP_NAME_DESCRIPTION: "YOUR APP DESCRIPTION NAME"
  IGRP_LOGIN_URL: "/login"
  IGRP_LOGOUT_URL: "/logout"
  IGRP_MINIO_URL: "TO BE DEFINED - minio-bucket_PUBLIC_DOMAIN"
  IGRP_NEXTAUTH_CALLBACK: ""
  IGRP_PREVIEW_MODE: "false"
  KEYCLOAK_ISSUER: "TO BE DEFINED - igrp-iam-keycloak_PUBLIC_DOMAIN/realms/igrp"
  NEXTAUTH_URL: "TO BE DEFINED - PUBLIC_DOMAIN"
