apiVersion: apps/v1
kind: Deployment
metadata:
  name: irn-process-management-demo-frontend
  labels:
    app: irn-process-management-demo-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: irn-process-management-demo-frontend
  template:
    metadata:
      labels:
        app: irn-process-management-demo-frontend
    spec:
      containers:
        - name: irn-process-management-demo-frontend
          image: irnzing/irn:irn-process-management-demo-frontend
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            env:
            - name: API_GATEWAY
              value: "https://${igrp-cloud-gateway-iE5d.RAILWAY_PUBLIC_DOMAIN}/igrp-platform-process-management"
            - name: IGRP_APP_BASE_PATH
              value: ""
            - name: IGRP_APP_CENTER_URL
              value: "https://${igrp-application-center.RAILWAY_PUBLIC_DOMAIN}"
            - name: IGRP_APP_CODE
              value: "APP_IGRP_CENTER"
            - name: IGRP_APP_HOME_SLUG
              value: "/fila-de-trabalho"
            - name: IGRP_APP_MANAGER_API
              value: "https://${igrp-cloud-gateway-iE5d.RAILWAY_PUBLIC_DOMAIN}/igrp-access-management"
            - name: IGRP_APP_NAME_DESCRIPTION
              value: "YOUR APP DESCRIPTION NAME"
            - name: IGRP_LOGIN_URL
              value: "/login"
            - name: IGRP_LOGOUT_URL
              value: "/logout"
            - name: IGRP_MINIO_URL
              value: "https://${minio-bucket-FNSX.RAILWAY_PUBLIC_DOMAIN}"
            - name: IGRP_NEXTAUTH_CALLBACK
              value: ""
            - name: IGRP_PREVIEW_MODE
              value: "false"
            - name: KEYCLOAK_CLIENT_ID
              value: "access-management"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "FTpKJk9kIT2LBCpzIAzCDZfHfjbqzWCy"
            - name: KEYCLOAK_ISSUER
              value: "https://${igrp-iam-keycloak-ztlw.RAILWAY_PUBLIC_DOMAIN}/realms/igrp"
            - name: NEXTAUTH_SECRET
              value: "AYNnFncwwTZSqlXzfuaYNpZSkHieaIxa"
            - name: NEXTAUTH_URL
              value: "https://${RAILWAY_PUBLIC_DOMAIN}"

